import React, { useEffect, useRef, useState } from 'react';
import { clamp, observeCanvas, setupCanvas } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C={bg:'#f5f8f0',env:'#b8c9a7',dark:'#76906a',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#f07e47',purple:'#7c3aed',text:'#21324a',muted:'#68778f',line:'#d7deea'};
function base(canvas:HTMLCanvasElement,w:number,h:number){const ctx=setupCanvas(canvas,w,h);ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h);return ctx}
const Analogy:React.FC<{mode:number}>=({mode})=>{const ref=useRef<HTMLCanvasElement>(null);const raf=useRef<number|null>(null);useEffect(()=>{const cv=ref.current;if(!cv)return;const ctx=setupCanvas(cv,560,140);let t=0;const draw=()=>{t+=.014;ctx.clearRect(0,0,560,140);ctx.fillStyle=C.bg;ctx.fillRect(0,0,560,140);const p=(Math.sin(t)+1)/2;if(mode===8){ctx.strokeStyle=C.line;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(65,90);ctx.bezierCurveTo(180,25,360,125,490,50);ctx.stroke();ctx.strokeStyle=C.blue;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(65,90);ctx.bezierCurveTo(65+120*p,90-65*p,65+300*p,90+35*p,65+425*p,90-40*p);ctx.stroke();ctx.fillStyle=C.orange;ctx.beginPath();ctx.arc(65+425*p,90-40*p,10,0,Math.PI*2);ctx.fill()}else if(mode===9){ctx.fillStyle=C.env;ctx.fillRect(100,56,360,22);ctx.fillStyle=C.orange;ctx.beginPath();ctx.arc(130+300*p,67,18,0,Math.PI*2);ctx.fill();ctx.strokeStyle=C.green;ctx.lineWidth=4;ctx.strokeRect(245,42,70,50)}else{ctx.fillStyle='#fff';ctx.strokeStyle=C.dark;ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(145,30,270,78,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.green;ctx.beginPath();ctx.arc(280,70,28*p,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 22px Segoe UI';ctx.textAlign='center';ctx.fillText('10',280,78)}cv.classList.add('is-ready');raf.current=requestAnimationFrame(draw)};const stop=()=>{if(raf.current)cancelAnimationFrame(raf.current);raf.current=null};const start=()=>{if(!raf.current)raf.current=requestAnimationFrame(draw)};const off=observeCanvas(cv,start,stop);return()=>{stop();off()}},[mode]);return <canvas ref={ref} width={560} height={140}/>};
export const C8Analogy:React.FC<WidgetProps>=()=> <Analogy mode={8}/>;
export const C9Analogy:React.FC<WidgetProps>=()=> <Analogy mode={9}/>;
export const C10Analogy:React.FC<WidgetProps>=()=> <Analogy mode={10}/>;

export const C8Arch:React.FC<WidgetProps>=()=>{const ref=useRef<HTMLCanvasElement>(null);const stages=['视频帧','视觉编码','Q-Former','记忆压缩','查询表示','Vicuna','答案'];const [active,setActive]=useState(0);useEffect(()=>{const cv=ref.current;if(!cv)return;const ctx=base(cv,1080,280);stages.forEach((s,i)=>{const x=30+i*148,sel=i===active,passed=i<active;ctx.fillStyle=sel?C.orange:passed?C.blue:'#fff';ctx.strokeStyle=sel?C.orange:passed?C.blue:C.line;ctx.lineWidth=sel?5:3;ctx.beginPath();ctx.roundRect(x,75,112,68,10);ctx.fill();ctx.stroke();if(i<6){ctx.strokeStyle=i<active?C.green:C.line;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+112,109);ctx.lineTo(x+145,109);ctx.stroke()}ctx.fillStyle=sel||passed?'#fff':C.text;ctx.font='bold 17px Segoe UI';ctx.textAlign='center';ctx.fillText(s,x+56,116)});ctx.fillStyle=C.text;ctx.font='bold 24px Segoe UI';ctx.fillText(active===1||active===5?'冻结':active===2||active===3?'微调路径':'数据状态',540,220);cv.classList.add('is-ready')},[active]);const notes=['输入第 t 帧。','视觉编码器冻结：产生 P×C 特征。','Q-Former 可训练：文本与视觉在此对齐。','逐层记忆压缩：最近全留，旧缓存排序。','长度受限的查询表示汇总长期视频。','Vicuna-7B 冻结：根据查询表示生成文本。','输出答案；本路线对应论文报告配置。'];return <div><canvas ref={ref} width={1080} height={280}/><div className="chip-row">{stages.map((s,i)=><button key={s} className={`chip ${active===i?'active':''}`} onClick={()=>setActive(i)}>{s}</button>)}</div><div className="ctrl-row"><button className="btn secondary" disabled={active===0} onClick={()=>setActive(active-1)}>上一步</button><button className="btn" disabled={active===6} onClick={()=>setActive(active+1)}>{active===6?'已到答案':'推进一段'}</button></div><div className={`feedback ${active===6?'good':''}`}>{notes[active]}</div></div>};

export const C9Tune:React.FC<WidgetProps>=()=>{const ref=useRef<HTMLCanvasElement>(null);const [a,setA]=useState(.1),[b,setB]=useState(.1);const retained=a+(1-a)*b;useEffect(()=>{const cv=ref.current;if(!cv)return;const ctx=base(cv,1080,280);ctx.fillStyle='#fff';ctx.strokeStyle=C.line;ctx.lineWidth=2;ctx.fillRect(90,35,620,200);ctx.strokeRect(90,35,620,200);for(let y=0;y<10;y++)for(let x=0;x<20;x++){const aa=.1+x*.03,bb=.1+y*.06;const d=Math.sqrt((aa-.1)**2+(bb-.1)**2);ctx.fillStyle=d<.16?'rgba(34,141,92,.55)':d<.35?'rgba(240,126,71,.35)':'rgba(196,63,82,.25)';ctx.fillRect(90+x*31,35+(9-y)*20,31,20)}const px=90+(a-.1)/.6*620,py=235-(b-.1)/.6*200;ctx.fillStyle=C.orange;ctx.beginPath();ctx.arc(px,py,12,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.blue;ctx.fillRect(790,205-retained*150,80,retained*150);ctx.fillStyle=C.text;ctx.font='bold 26px Segoe UI';ctx.textAlign='center';ctx.fillText(`r=${retained.toFixed(2)}`,830,235);cv.classList.add('is-ready')},[a,b]);const set=(x:number,y:number)=>{setA(x);setB(y)};const balanced=Math.abs(a-.1)<.02&&Math.abs(b-.1)<.02,high=a>.45||b>.45;return <div><canvas ref={ref} width={1080} height={280}/><div className="chip-row"><button className="chip" onClick={()=>set(.1,.05)}>健忘</button><button className={`chip ${balanced?'active':''}`} onClick={()=>set(.1,.1)}>论文设置</button><button className="chip" onClick={()=>set(.65,.65)}>囤积</button></div><div className="ctrl"><label>α <span className="val">{a.toFixed(2)}</span></label><input type="range" aria-label="最近比例 α" min="10" max="70" value={a*100} onChange={e=>setA(+e.target.value/100)}/><label>β <span className="val">{b.toFixed(2)}</span></label><input type="range" aria-label="旧缓存保留比例 β" min="5" max="70" value={b*100} onChange={e=>setB(+e.target.value/100)}/></div><div className={`feedback ${balanced?'good':high?'bad':''}`}>有效保留因子 r={retained.toFixed(2)}；{balanced?'论文报告配置：在其消融中平衡准确率与显存。':high?'保留更多 token 会增加显存，准确率也并非单调上升。':'过度遗忘可能删掉答案线索；绿色区域仅表示论文趋势。'}</div></div>};

type Metric={label:string,base:number,ours:number,max:number,unit:string,note:string};
const metrics:Record<string,Metric>={lvu:{label:'LVU 平均',base:63,ours:67.5,max:80,unit:'Top-1 %',note:'七项任务平均，同表比较。'},breakfast:{label:'Breakfast',base:93,ours:94.4,max:100,unit:'Top-1 %',note:'同一数据集，越高越好。'},coin:{label:'COIN',base:93.2,ours:93.3,max:100,unit:'Top-1 %',note:'提升仅 0.1 个百分点。'},msvd:{label:'MSVD',base:179.1,ours:189.4,max:210,unit:'CIDEr',note:'仅限 MSVD 描述任务。'},memory:{label:'显存',base:100,ours:35,max:100,unit:'相对量',note:'最高/接近减少 65%，仅限论文设置。'}};
export const C10Results:React.FC<WidgetProps>=()=>{const ref=useRef<HTMLCanvasElement>(null);const [metric,setMetric]=useState('lvu'),[started,setStarted]=useState(false),[clue,setClue]=useState(false);const m=metrics[metric];useEffect(()=>{const cv=ref.current;if(!cv)return;const ctx=base(cv,1080,280);const frac=started?1:.08;const higher=metric!=='memory';const b=m.base/m.max*700*frac,o=m.ours/m.max*700*frac;ctx.fillStyle=C.red;ctx.fillRect(210,75,b,44);ctx.fillStyle=higher?C.green:C.green;ctx.fillRect(210,155,o,44);ctx.fillStyle=C.text;ctx.font='bold 24px Segoe UI';ctx.textAlign='right';ctx.fillText('MA-LMM',190,105);ctx.fillText('AdaCM²',190,185);ctx.textAlign='left';ctx.fillText(started?`${m.base}`:'',225+b,105);ctx.fillText(started?`${m.ours}`:'',225+o,185);if(clue){ctx.fillStyle=C.green;ctx.beginPath();ctx.arc(990,55,35,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 25px Segoe UI';ctx.textAlign='center';ctx.fillText('10',990,64)}cv.classList.add('is-ready')},[metric,started,clue,m]);return <div><canvas ref={ref} width={1080} height={280}/><div className="chip-row">{Object.entries(metrics).map(([k,v])=><button key={k} className={`chip ${metric===k?'active':''}`} onClick={()=>{setMetric(k);setStarted(false);setClue(false)}}>{v.label}</button>)}</div><div className="ctrl-row"><button className="btn" onClick={()=>setStarted(true)}>开始比较</button><button className="btn secondary" onClick={()=>setClue(true)}>打开保留线索</button></div><div className={`feedback ${started?'good':''}`}>{!started?'选择兼容指标，再启动同一协议下的比较。':metric==='memory'?`${m.note} 该视图是相对示意，不是通用固定比例。`:`${m.label}：${m.base} → ${m.ours} ${m.unit}。${m.note}`}{clue?' Ego4D 定性案例中的球衣号码为 10。':''}</div></div>};
