import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { C1Analogy } from './adacm2-c1-analogy';
import { C1Clue } from './adacm2-c1-clue';
import { C1Pressure } from './adacm2-c1-pressure';
import { C10Analogy } from './adacm2-c10-analogy';
import { C10Results } from './adacm2-c10-results';
import { C2Analogy } from './adacm2-c2-analogy';
import { C2Query } from './adacm2-c2-query';
import { C3Analogy } from './adacm2-c3-analogy';
import { C3Layer } from './adacm2-c3-layer';
import { C3Sparse } from './adacm2-c3-sparse';
import { C4Analogy } from './adacm2-c4-analogy';
import { C4Step } from './adacm2-c4-step';
import { C5Analogy } from './adacm2-c5-analogy';
import { C5Score } from './adacm2-c5-score';
import { C6Analogy } from './adacm2-c6-analogy';
import { C6Cleaner } from './adacm2-c6-cleaner';
import { C7Analogy } from './adacm2-c7-analogy';
import { C7Limit } from './adacm2-c7-limit';
import { C8Analogy } from './adacm2-c8-analogy';
import { C8Arch } from './adacm2-c8-arch';
import { C9Analogy } from './adacm2-c9-analogy';
import { C9Tune } from './adacm2-c9-tune';
import { HeroNew } from './adacm2-hero-new';
import { HeroOld } from './adacm2-hero-old';
import { C2Map, C4Cache, C4LayerDistance, C5Arena, C6Rescue, C7LayerBoard, C8Stepper, C9Evidence, C10Timeline } from './adacm2-upgrade-modules';
import { C1PressureV3, C3Microscope, C6Surgery, C8Trace, C10Mystery } from './adacm2-flagship-modules';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['adacm2-c1-analogy'] = C1Analogy;
widgetRegistry['adacm2-c1-clue'] = C1Clue;
widgetRegistry['adacm2-c1-pressure'] = C1Pressure;
widgetRegistry['adacm2-c1-pressure-v3'] = C1PressureV3;
widgetRegistry['adacm2-c10-analogy'] = C10Analogy;
widgetRegistry['adacm2-c10-results'] = C10Results;
widgetRegistry['adacm2-c10-timeline'] = C10Timeline;
widgetRegistry['adacm2-c10-mystery'] = C10Mystery;
widgetRegistry['adacm2-c2-analogy'] = C2Analogy;
widgetRegistry['adacm2-c2-query'] = C2Query;
widgetRegistry['adacm2-c2-map'] = C2Map;
widgetRegistry['adacm2-c3-analogy'] = C3Analogy;
widgetRegistry['adacm2-c3-layer'] = C3Layer;
widgetRegistry['adacm2-c3-sparse'] = C3Sparse;
widgetRegistry['adacm2-c3-microscope'] = C3Microscope;
widgetRegistry['adacm2-c4-analogy'] = C4Analogy;
widgetRegistry['adacm2-c4-step'] = C4Step;
widgetRegistry['adacm2-c4-cache'] = C4Cache;
widgetRegistry['adacm2-c4-layer-distance'] = C4LayerDistance;
widgetRegistry['adacm2-c5-analogy'] = C5Analogy;
widgetRegistry['adacm2-c5-score'] = C5Score;
widgetRegistry['adacm2-c5-arena'] = C5Arena;
widgetRegistry['adacm2-c6-analogy'] = C6Analogy;
widgetRegistry['adacm2-c6-cleaner'] = C6Cleaner;
widgetRegistry['adacm2-c6-rescue'] = C6Rescue;
widgetRegistry['adacm2-c6-surgery'] = C6Surgery;
widgetRegistry['adacm2-c7-analogy'] = C7Analogy;
widgetRegistry['adacm2-c7-limit'] = C7Limit;
widgetRegistry['adacm2-c7-layer-board'] = C7LayerBoard;
widgetRegistry['adacm2-c8-analogy'] = C8Analogy;
widgetRegistry['adacm2-c8-arch'] = C8Arch;
widgetRegistry['adacm2-c8-stepper'] = C8Stepper;
widgetRegistry['adacm2-c8-trace'] = C8Trace;
widgetRegistry['adacm2-c9-analogy'] = C9Analogy;
widgetRegistry['adacm2-c9-tune'] = C9Tune;
widgetRegistry['adacm2-c9-evidence'] = C9Evidence;
widgetRegistry['adacm2-hero-new'] = HeroNew;
widgetRegistry['adacm2-hero-old'] = HeroOld;
