import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { SharedRoot } from './shared';
import { VC1A } from './vc-1-a';
import { VC1B } from './vc-1-b';
import { VC10A } from './vc-10-a';
import { VC10B } from './vc-10-b';
import { VC2A } from './vc-2-a';
import { VC2B } from './vc-2-b';
import { VC3A } from './vc-3-a';
import { VC3B } from './vc-3-b';
import { VC4A } from './vc-4-a';
import { VC4B } from './vc-4-b';
import { VC5A } from './vc-5-a';
import { VC5B } from './vc-5-b';
import { VC6A } from './vc-6-a';
import { VC6B } from './vc-6-b';
import { VC7A } from './vc-7-a';
import { VC7B } from './vc-7-b';
import { VC8A } from './vc-8-a';
import { VC8B } from './vc-8-b';
import { VC9A } from './vc-9-a';
import { VC9B } from './vc-9-b';
import { Analogy1 } from './vc-analogy-1';
import { Analogy10 } from './vc-analogy-10';
import { Analogy2 } from './vc-analogy-2';
import { Analogy3 } from './vc-analogy-3';
import { Analogy4 } from './vc-analogy-4';
import { Analogy5 } from './vc-analogy-5';
import { Analogy6 } from './vc-analogy-6';
import { Analogy7 } from './vc-analogy-7';
import { Analogy8 } from './vc-analogy-8';
import { Analogy9 } from './vc-analogy-9';
import { HeroNew } from './vc-hero-new';
import { HeroOld } from './vc-hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['shared'] = SharedRoot;
widgetRegistry['vc-1-a'] = VC1A;
widgetRegistry['vc-1-b'] = VC1B;
widgetRegistry['vc-10-a'] = VC10A;
widgetRegistry['vc-10-b'] = VC10B;
widgetRegistry['vc-2-a'] = VC2A;
widgetRegistry['vc-2-b'] = VC2B;
widgetRegistry['vc-3-a'] = VC3A;
widgetRegistry['vc-3-b'] = VC3B;
widgetRegistry['vc-4-a'] = VC4A;
widgetRegistry['vc-4-b'] = VC4B;
widgetRegistry['vc-5-a'] = VC5A;
widgetRegistry['vc-5-b'] = VC5B;
widgetRegistry['vc-6-a'] = VC6A;
widgetRegistry['vc-6-b'] = VC6B;
widgetRegistry['vc-7-a'] = VC7A;
widgetRegistry['vc-7-b'] = VC7B;
widgetRegistry['vc-8-a'] = VC8A;
widgetRegistry['vc-8-b'] = VC8B;
widgetRegistry['vc-9-a'] = VC9A;
widgetRegistry['vc-9-b'] = VC9B;
widgetRegistry['vc-analogy-1'] = Analogy1;
widgetRegistry['vc-analogy-10'] = Analogy10;
widgetRegistry['vc-analogy-2'] = Analogy2;
widgetRegistry['vc-analogy-3'] = Analogy3;
widgetRegistry['vc-analogy-4'] = Analogy4;
widgetRegistry['vc-analogy-5'] = Analogy5;
widgetRegistry['vc-analogy-6'] = Analogy6;
widgetRegistry['vc-analogy-7'] = Analogy7;
widgetRegistry['vc-analogy-8'] = Analogy8;
widgetRegistry['vc-analogy-9'] = Analogy9;
widgetRegistry['vc-hero-new'] = HeroNew;
widgetRegistry['vc-hero-old'] = HeroOld;
