import { useState } from 'react';
import { Chips, Feedback, Quiz, EvidenceFigure, C } from './shared';
const cases=[
{fig:4,title:'梗图：看见人物，等于懂梗吗？',tag:'幽默理解',clues:['人物','环境'],visible:'先观察画面中的人物、动作及场景，再区分画面可见信息与网络文化背景。',interpret:'本例涉及 meme / rickroll 文化梗。论文展示的回答提到观众可能觉得“被骗”，但没有明确说出 Rickroll 梗。',limit:'这段回答触及期待落差，仍不能仅凭一个案例证明模型理解了完整的文化语境。'},
{fig:5,title:'Why is it funny?',tag:'幽默理解',clues:['动作','环境'],visible:'寻找画面中动作与情境的不协调之处。哪些细节可以直接指出，哪些需要观众的常识？',interpret:'论文用这个例子展示对视频幽默的解释。请对照原回答，逐句区分描述与解释。',limit:'一个幽默案例不构成幽默理解的系统评测，解释也可能存在主观性。'},
{fig:6,title:'事故：事件发生了，原因呢？',tag:'因果推断',clues:['动作','时间','环境'],visible:'关注物体的相对位置、动作变化及事发前后顺序。先建立可观察的事件链。',interpret:'论文展示事故相关的视频理解问答。可见事件能支持描述，但原因判断还需要更完整的上下文。',limit:'发生在前不等于导致后果，不能仅凭案例回答确定责任或排除其他原因。'},
{fig:7,title:'这段视频适合什么音乐？',tag:'创意配乐',clues:['动作','环境'],visible:'留意动作节奏、场景与氛围。它们可以成为配乐建议的依据。',interpret:'论文展示根据视频内容提出音乐建议的案例；这是开放式创意回应。',limit:'配乐建议具有偏好性，不是一个有唯一标准答案的分类得分。'},
{fig:8,title:'篮球之后，何时开始跳舞？',tag:'多轮对话',clues:['动作','时间'],visible:'观察动作切换，结合原图中连续追问的上下文。',interpret:'VideoChat-Embed 的示例回答包含室内球场、相机基本固定，以及约 9.8 秒开始跳舞。',limit:'9.8 秒是模型回答，不是定位误差；一个多轮示例不能证明所有追问都可靠。'},
{fig:9,title:'屋顶活动：建议与安全事实',tag:'安全建议',clues:['人物','动作','环境'],visible:'检查人物活动和周围环境；也要记录画面没有提供的条件。',interpret:'VideoChat-Text 的案例包含对活动与安全的讨论。对照原文，留意模型何时由可见描述转向判断。',limit:'该案例无法验证屋顶安全。结构状况、现场条件等未必可见，模型建议不构成安全认证。'}
];
const clueNames=['人物','动作','时间','环境','因果'];
export function VC9B(){const [index,setIndex]=useState(0),[clues,setClues]=useState<string[]>([]),[reveal,setReveal]=useState(false),[filter,setFilter]=useState(0);const filters=['全部','幽默理解','因果推断','创意配乐','多轮对话','安全建议'];const item=cases[index];const change=(i:number)=>{setIndex(i);setClues([]);setReveal(false);};const filtered=cases.map((c,i)=>({c,i})).filter(({c})=>filter===0||c.tag===filters[filter]);return <div><p>这里收藏的是 <strong>定性案例，不是成绩榜</strong>。先判断所需线索，再打开原图核对回答：可见证据、模型解释、可靠性结论是三件不同的事。</p><Chips options={filters} value={filter} onChange={v=>{setFilter(v);change(v===0?0:cases.findIndex(c=>c.tag===filters[v]));}}/><div style={{display:'flex',gap:9,overflowX:'auto',padding:'14px 0'}}>{filtered.map(({c,i})=><button key={c.fig} className={'chip '+(i===index?'selected':'')} aria-pressed={i===index} onClick={()=>change(i)} style={{minWidth:150,whiteSpace:'normal',padding:16}}>Fig.{c.fig}<br/>{c.title}</button>)}</div><div style={{border:'1px solid '+C.edge,borderRadius:16,padding:20}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><button className="chip" onClick={()=>{setFilter(0);change((index+5)%6);}}>← 上一案例</button><strong>Fig.{item.fig} · {item.tag}</strong><button className="chip" onClick={()=>{setFilter(0);change((index+1)%6);}}>下一案例 →</button></div><h4>{item.title}</h4><p>这个问题至少需要什么线索？可多选。</p><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{clueNames.map(c=><button key={c} className={'chip '+(clues.includes(c)?'selected':'')} aria-pressed={clues.includes(c)} onClick={()=>{setClues(s=>s.includes(c)?s.filter(x=>x!==c):[...s,c]);setReveal(false);}}>{c}</button>)}</div><p><button className="chip" disabled={clues.length===0} onClick={()=>setReveal(v=>!v)}>{reveal?'收起案例解读':'我已选择线索，揭晓案例'}</button> {clues.length===0&&<span>先选择至少一条线索。</span>}</p>{reveal&&<><Feedback tone="info">你选择了 {clues.join('、')}。建议重点检查 {item.clues.join('、')}；这些是教学审阅提示，不是论文给出的唯一线索标注。</Feedback><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:14}}>{[['① 可见证据',item.visible],['② 模型解释',item.interpret],['③ 不能证明',item.limit]].map(([title,text])=><div key={title} style={{background:C.bg,padding:16,borderRadius:12}}><b>{title}</b><p>{text}</p></div>)}</div><EvidenceFigure src={'./images/fig'+item.fig+'.png'} title={'论文 Fig.'+item.fig+' · 原图与原始回答'}><p>{item.interpret} {item.limit}</p></EvidenceFigure></>}</div><p>读案例的正确节奏：指认画面 → 读取原答 → 检查推断跨度 → 保留结论边界。Fig.4–9 展示了多种应用潜力，同时也暴露了文化理解、因果与安全判断的证据缺口。</p><Quiz chapter={9} questions={[{q:'论文实验的主要证据类型是什么？',options:['大规模统一定量 leaderboard','Qualitative case studies（定性案例）','用户问卷','理论证明'],answer:1,explanation:'论文以初步定性实验和案例展示能力，没有给出可据此比较总体准确率的统一榜单。'},{q:'“什么时候开始跳舞？”比“他穿什么衣服？”更依赖哪种信息？',options:['时间信息','文字字体','图像分辨率','模型参数数量'],answer:0,explanation:'回答“什么时候”需要定位动作随时间的变化，衣服描述通常可以从单帧获得。'}]}/></div>}
