import React, { useEffect, useRef, useState } from 'react';
import { setupCanvas, observeCanvas } from '../lib/canvasKit';

export const C={bg:'#f5f8f0',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#f07e47',purple:'#7c3aed',text:'#21324a',muted:'#68778f',edge:'#d7deea',pale:'#b8c9a7',dark:'#76906a',brown:'#92400e'};
export function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string,r=10){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=color;ctx.fill();}
export function line(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,color:string,width=3){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
export function person(ctx:CanvasRenderingContext2D,x:number,y:number,scale=1,pose=0,color=C.blue){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.arc(0,-36,10,0,Math.PI*2);ctx.fill();line(ctx,0,-22,0,9,color,6);line(ctx,0,-16,-23,-8-Math.sin(pose)*18,color,5);line(ctx,0,-16,24,-8+Math.sin(pose)*17,color,5);line(ctx,0,9,-16,39,color,5);line(ctx,0,9,16+Math.sin(pose)*10,37,color,5);ctx.restore();}
export function filmFrame(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,index:number,active=false){rounded(ctx,x,y,w,h,active?'#e6f0e8':'#edf0eb',7);ctx.strokeStyle=active?C.green:C.edge;ctx.lineWidth=active?4:2;ctx.strokeRect(x+1,y+1,w-2,h-2);for(let k=0;k<5;k++){rounded(ctx,x+7+k*(w-18)/5,y+5,7,4,C.pale,1);rounded(ctx,x+7+k*(w-18)/5,y+h-9,7,4,C.pale,1);}line(ctx,x+9,y+h-19,x+w-9,y+h-19,C.pale,2);person(ctx,x+w*.52,y+h*.53,Math.min(w/95,h/115),index*.85,active?C.blue:C.dark);if(index<3){ctx.beginPath();ctx.arc(x+w*.75,y+h*(.5+index*.12),w*.06,0,Math.PI*2);ctx.fillStyle=C.orange;ctx.fill();}}
type SceneProps=Omit<React.CanvasHTMLAttributes<HTMLCanvasElement>,'height'|'width'> & {draw:(ctx:CanvasRenderingContext2D,w:number,h:number,time:number)=>void;height?:number;width?:number;animate?:boolean;label?:string};
export function Scene({draw,height=280,width=1080,animate=false,label='交互教学画布',onKeyDown,style,...rest}:SceneProps){
 const ref=useRef<HTMLCanvasElement>(null);const painter=useRef(draw);painter.current=draw;const redraw=useRef<()=>void>(()=>{});
 useEffect(()=>{const cv=ref.current;if(!cv)return;const ctx=setupCanvas(cv,width,height);cv.style.width='100%';cv.style.height='auto';let raf=0,visible=false,hover=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const paint=()=>{ctx.clearRect(0,0,width,height);ctx.fillStyle=C.bg;ctx.fillRect(0,0,width,height);painter.current(ctx,width,height,reduced?0:performance.now()/1000);cv.classList.add('is-ready');};
 const tick=()=>{paint();raf=animate&&visible&&!hover&&!reduced?requestAnimationFrame(tick):0;};const stop=()=>{cancelAnimationFrame(raf);raf=0;};const start=()=>{visible=true;if(!raf)tick();};const leave=()=>{visible=false;stop();};const enterHover=()=>{hover=true;stop();};const exitHover=()=>{hover=false;if(visible)start();};
 redraw.current=paint;paint();const disconnect=observeCanvas(cv,start,leave);if(animate){cv.addEventListener('mouseenter',enterHover);cv.addEventListener('mouseleave',exitHover);}return()=>{stop();disconnect();cv.removeEventListener('mouseenter',enterHover);cv.removeEventListener('mouseleave',exitHover);};
 },[height,width,animate]);useEffect(()=>redraw.current(),[draw]);
 return <canvas ref={ref} aria-label={label} role="img" {...rest} style={{display:'block',width:'100%',height:'auto',aspectRatio:`${width}/${height}`,borderRadius:10,touchAction:rest.onPointerDown?'none':'auto',...style}} onKeyDown={e=>{if(e.key.startsWith('Arrow'))e.stopPropagation();onKeyDown?.(e);}}/>;
}
export function Chips({options,value,onChange}:{options:string[];value:number;onChange:(v:number)=>void}){return <div className="ctrl" style={{flexWrap:'wrap'}}>{options.map((v,i)=><button type="button" className={`chip ${i===value?'selected':''}`} aria-pressed={i===value} onClick={()=>onChange(i)} key={v}>{v}</button>)}</div>;}
export function Feedback({children,tone='info'}:{children:React.ReactNode;tone?:'good'|'bad'|'info'|'warn'}){return <div className={`feedback ${tone==='good'?'good':tone==='bad'?'bad':''}`} role="status" style={tone==='warn'?{borderLeftColor:C.orange,background:'#fff7ed'}:undefined}>{children}</div>;}
export interface QuizQuestion {q:string;options:string[];answer:number;explanation:string}
export function Quiz({chapter,questions}:{chapter:number;questions:QuizQuestion[]}){const[answers,setAnswers]=useState<Record<number,number>>({});return <details style={{marginTop:24,border:'1px solid '+C.edge,borderRadius:10,padding:'14px 18px',background:'#fff'}}><summary style={{cursor:'pointer',fontWeight:700,color:C.blue}}>本章挑战 · 2 道可选小测</summary><p style={{margin:'12px 0',color:C.muted}}>可随时收起、反复作答；不会影响进入下一章。</p>{questions.map((q,i)=><details key={i} style={{padding:'12px 0',borderTop:'1px solid '+C.edge}}><summary style={{cursor:'pointer',fontWeight:600}}>{i+1}. {q.q}</summary><div className="ctrl" style={{display:'grid',gap:8,marginTop:12}}>{q.options.map((o,j)=><button key={j} type="button" className={`chip ${answers[i]===j?'selected':''}`} aria-pressed={answers[i]===j} onClick={()=>setAnswers(a=>({...a,[i]:j}))} style={{textAlign:'left',whiteSpace:'normal'}}>{String.fromCharCode(65+j)}. {o}</button>)}</div>{answers[i]!==undefined&&<Feedback tone={answers[i]===q.answer?'good':'bad'}>{answers[i]===q.answer?'✓ 对，就是这个逻辑。':'还差一点，可以再选一次。'} {q.explanation}</Feedback>}</details>)}<span style={{display:'none'}}>{chapter}</span></details>;}
export function EvidenceFigure({src,title,children}:{src:string;title:string;children?:React.ReactNode}){const dlg=useRef<HTMLDialogElement>(null);const [translate,setTranslate]=useState(false);return <details style={{margin:'18px 0',border:'1px solid '+C.edge,borderRadius:10,padding:12}}><summary style={{cursor:'pointer',fontWeight:600,color:C.blue}}>原论文证据 · {title}</summary><div className="ctrl"><button className="chip" onClick={()=>dlg.current?.showModal()}>放大原图</button>{children&&<button className={`chip ${translate?'selected':''}`} onClick={()=>setTranslate(v=>!v)}>{translate?'显示原图':'中文解释'}</button>}</div>{translate&&children?<div>{children}</div>:<img src={src} alt={title} loading="lazy" style={{display:'block',maxWidth:'100%',maxHeight:440,margin:'auto',objectFit:'contain'}}/>}<dialog ref={dlg} aria-label={title} onKeyDown={e=>e.stopPropagation()} onClick={e=>{if(e.target===e.currentTarget)dlg.current?.close();}} style={{maxWidth:'92vw',width:1100,maxHeight:'92vh',padding:20,border:'1px solid '+C.edge,borderRadius:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',position:'sticky',top:0,background:'white',padding:8}}><strong>{title}</strong><button className="chip" autoFocus onClick={()=>dlg.current?.close()}>关闭原图</button></div><img src={src} alt={title} style={{width:'100%',height:'auto'}}/>{children&&<div style={{marginTop:16}}>{children}</div>}</dialog></details>;}
export function SharedRoot(){return null;}
