import React, { useMemo, useState } from 'react';

type Props = { variant?: string };
const Badge = ({ children, tone = 'paper' }: { children: React.ReactNode; tone?: string }) => <span className={`vl-badge ${tone}`}>{children}</span>;
const Choice = ({ items, value, onChange }: { items: string[]; value: string; onChange: (v: string) => void }) => <div className="vl-choices">{items.map(x => <button key={x} className={x === value ? 'selected' : ''} onClick={() => onChange(x)}>{x}</button>)}</div>;
const Readout = ({ children }: { children: React.ReactNode }) => <div className="vl-readout">{children}</div>;

export function TimelineLab({ variant }: Props) {
  const [frame, setFrame] = useState(0);
  const [mode, setMode] = useState('完整画面');
  const frames = ['I','P','P','P','P','I','P','P','P','P','P','I'];
  return <div className="vl-lab"><div className="vl-lab-top"><Badge>教学模拟 · MPEG-4 序列示例</Badge><Choice items={['完整画面','解耦表示']} value={mode} onChange={setMode}/></div>
    <div className="vl-film">{frames.map((f,i)=><button key={i} className={`${i===frame?'selected':''} ${f==='I'?'keyframe':''}`} onClick={()=>setFrame(i)}><b>{f}</b><small>{i+1}</small></button>)}</div>
    <div className="vl-scene"><div className="vl-landscape"><span className="vl-sun"/><span className="vl-hill"/><span className="vl-car" style={{left:`${18+frame*5}%`}}/></div><div className="vl-scene-notes"><strong>{mode==='完整画面'?'每帧都观察整幅画面':frames[frame]==='I'?'I-frame 保留完整视觉语义':'P-frame 以预测和运动信息描述变化'}</strong><span>{frames[frame]==='I'?'这里是一张 I-frame；论文直接把压缩视频中的 I-frame 当关键帧。':'相对于前一张参考画面，移动物体的宏块可以用位移描述。'}</span></div></div>
    <Readout>第 {frame+1} 帧 · {frames[frame]}-frame · <b>{mode==='解耦表示'?'外观与运动分开编码':'相邻帧背景高度重复'}</b>。此时间轴只演示压缩视频结构，不代表论文固定每隔几帧选一张 I-frame。</Readout></div>;
}

export function CostLab({ variant }: Props) {
  const [method,setMethod]=useState('VideoPoet'); const [seconds,setSeconds]=useState(2.2);
  const description: Record<string,string>={ '逐帧视觉编码':'每帧分别送入视觉编码器；序列长度随帧数增加。论文未报告这里的统一 token 数。','VideoPoet':'论文引述：2.2 秒视频约 1280 tokens。','Video-LaVIT':'论文配置：24 帧、6 fps 的 clip，平均约 90 visual tokens + 135 motion tokens。'};
  if(variant==='role'){const [role,setRole]=useState('Visual');return <div className="vl-lab"><Choice items={['Visual','Motion','Text']} value={role} onChange={setRole}/><div className="vl-role-card"><div className={`vl-role-symbol ${role.toLowerCase()}`}>{role==='Visual'?'▣':role==='Motion'?'↗':'Aa'}</div><div><h4>{role} tokens 的职责</h4><p>{role==='Visual'?'关键帧的外观与语义；继承 LaVIT 视觉词典。':role==='Motion'?'压缩视频的宏块位移经过运动 tokenizer 离散化。':'问题、描述与回答进入同一个自回归序列。'}</p></div></div><Readout>统一 next-token 目标不意味着三个 token 类型承担相同的信息。</Readout></div>}
  return <div className="vl-lab"><Badge tone="demo">论文示例 + 教学外推 · Introduction / Appendix A.1</Badge><Choice items={['逐帧视觉编码','VideoPoet','Video-LaVIT']} value={method} onChange={setMethod}/><div className="vl-cost-compare"><div className="vl-cost-number">{method==='VideoPoet'?'1280':method==='Video-LaVIT'?'≈225':'随帧数增加'}<small>{method==='逐帧视觉编码'?'':' tokens'}</small></div><div>{description[method]}</div></div><small className="vl-note">VideoPoet 示例为 2.2 秒，Video-LaVIT 的 24 帧 @ 6 fps 为 4 秒；两者并非同协议的直接压缩率对比。</small>{variant==='scale'&&<label className="vl-range">视频时长（仅线性示意）<input type="range" min="2.2" max="13.2" step="1.1" value={seconds} onChange={e=>setSeconds(+e.target.value)}/><strong>{seconds.toFixed(1)} 秒</strong></label>}{variant==='scale'&&<Readout>{method==='VideoPoet'?`按 2.2 秒示例等比例外推约 ${Math.round(1280*seconds/2.2)} tokens。论文没有报告该时长的实测值。`:method==='Video-LaVIT'?`约 ${Math.round(seconds/4*225)} tokens（按 4 秒 clip 线性估算，不含文本和边界标记）。`:'逐帧方案缺少同协议的 token 数，不能作数值比较。'}</Readout>}</div>
}

export function MpegLab({ variant }: Props) {
  const [selected,setSelected]=useState(0); const [radius,setRadius]=useState(2); const [dx,setDx]=useState(0); const [dy,setDy]=useState(0);
  const frames=['I','P','P','P','I','P','P'];
  const target={x:1,y:-1}; const error=Math.abs(dx-target.x)*11+Math.abs(dy-target.y)*9;
  if(variant==='search'||variant==='eq1') return <div className="vl-lab"><Badge>Eq.1 · 16×16 macroblock</Badge><div className="vl-block-layout"><div className="vl-search-window"><div className="vl-block-title">前一帧的搜索窗口</div><div className="vl-block-grid">{Array.from({length:25},(_,i)=>{const x=i%5-2,y=Math.floor(i/5)-2;return <button key={i} disabled={Math.abs(x)>radius||Math.abs(y)>radius} className={`${x===dx&&y===dy?'selected':''} ${x===target.x&&y===target.y?'target':''}`} onClick={()=>{setDx(x);setDy(y)}} title={`位移 (${x},${y})`}>{x===target.x&&y===target.y?'▣':'·'}</button>})}</div><small>橙框＝当前候选　绿格＝最低差异位置</small></div><div className="vl-vector-link"><span>位移向量</span><i>⟶</i><b>({dx}, {dy})</b><small>把搜索到的块移回当前帧</small></div><div className="vl-block-current"><div className="vl-block-title">当前帧完整画面</div><div className="vl-match-frame"><i className="vl-frame-center"/><span className="vl-macroblock" style={{left:`${50+dx*9}%`,top:`${50+dy*9}%`}}>▦</span></div><p>候选位移 <b>({dx}, {dy})</b></p><p>教学模拟差异 <b>{error}</b><span className="vl-muted"> · 越低越接近</span></p></div></div>{variant==='search'&&<label className="vl-range">搜索半径 <input type="range" min="0" max="2" value={radius} onChange={e=>setRadius(+e.target.value)}/><strong>{radius} · {(radius*2+1)**2} 个候选</strong></label>}<Readout>{error===0?'✓ 当前候选误差最小，得到 motion vector (1, −1)。':`继续选择候选块。搜索 ${((radius*2+1)**2)} 个位置时，最低差异格${radius>=1?'可被找到':'落在当前搜索窗口外'}。`} <span className="vl-muted">格子和差异值为教学模拟；论文 Eq.1 定义的是最小化宏块差异。</span></Readout></div>;
  return <div className="vl-lab"><Badge>论文证据 · Section 3.1 / Figure 2</Badge><div className="vl-film compact">{frames.map((f,i)=><button key={i} className={`${selected===i?'selected':''} ${f==='I'?'keyframe':''}`} onClick={()=>setSelected(i)}><b>{f}</b><small>{i+1}</small></button>)}</div><div className="vl-decompose"><div className={frames[selected]==='I'?'lit':''}>▣<strong>I-frame</strong><span>直接保留关键画面</span></div><div className={frames[selected]==='P'?'lit':''}>↗<strong>Motion vectors</strong><span>描述 16×16 宏块位移</span></div></div><Readout>{frames[selected]==='I'?'作者把压缩视频已有的 I-frame 作为关键帧。':'motion vector 可在压缩视频解码时快速提取；这里不需要额外计算密集光流。'}</Readout></div>;
}

export function VisualLab({variant}:Props){const [step,setStep]=useState(variant==='count'?3:0);const [view,setView]=useState(variant==='count'?'数量':variant==='codebook'?'词典':'语义');const steps=['224×224 keyframe','EVA-CLIP ViT-G/14','LaVIT visual tokenizer','平均约 90 tokens'];return <div className="vl-lab"><Badge>论文证据 · Appendix A.1</Badge><div className="vl-pipeline">{steps.map((s,i)=><button key={s} className={i===step?'selected':''} onClick={()=>setStep(i)}><span>{String(i+1).padStart(2,'0')}</span>{s}</button>)}</div><div className="vl-visual-diagram"><div className="vl-image-tile">🌄</div><span>→</span><div className="vl-token-cloud">{Array.from({length:step===3?18:step===2?12:6},(_,i)=><i key={i}/>)}</div></div><Choice items={['语义','数量','词典']} value={view} onChange={setView}/><Readout>{view==='语义'?'视觉分支复用 LaVIT，保留图像预训练获得的视觉先验。':view==='数量'?'论文报告每张 keyframe 平均约 90 个 visual tokens；示意格子不逐个画出 90 个。':'视觉 codebook 容量为 16,384；这是可选 token ID 的数量，而非每帧的 token 数。'}</Readout></div>}

export function MotionFold({variant}:Props){const [step,setStep]=useState(0);const stages=[['输入','24 帧 × 20 × 36 × 2','6 fps 连续 24 帧；向量按视频宽高归一化'],['编码','12 个 Transformer blocks','空间/时间注意力；第 3、6、9、12 层后下采样'],['潜变量','3 × 9 × 5','最终 135 个 latent vectors'],['量化','1024-entry codebook','投影到 32 维，L2 归一化后找最近码字'],['输出','135 motion tokens','离散 ID 可进入 LLM 的序列']];return <div className="vl-lab"><Badge>论文证据 · Appendix A.1 / Eq.2</Badge><div className="vl-fold-heading"><strong>{stages[step][0]}</strong><span>{stages[step][1]}</span></div><div className="vl-fold-grid" style={{gridTemplateColumns:`repeat(${step<2?12:9},1fr)`}}>{Array.from({length:step<2?72:step===2?45:27},(_,i)=><i key={i} className={step>=3?'quantized':''}/>)}</div><div className="vl-stepper"><button onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0}>← 上一步</button><div>{stages.map((_,i)=><button key={i} aria-label={`第 ${i+1} 步`} className={i===step?'selected':''} onClick={()=>setStep(i)}>{i+1}</button>)}</div><button onClick={()=>setStep(Math.min(4,step+1))} disabled={step===4}>下一步 →</button></div><Readout>{stages[step][2]}。<span className="vl-muted">图形是张量维度的教学抽象，不按真实单元数绘制。</span></Readout>{variant==='depth'&&<div className="vl-layer-strip">{Array.from({length:12},(_,i)=><span className={i<=(step+1)*2?'on':''} key={i}>{i+1}{[3,6,9,12].includes(i+1)?' ↓':''}</span>)}</div>}</div>}

const codes=[{id:101,x:-0.92,y:0.39},{id:317,x:0.75,y:0.67},{id:812,x:-0.05,y:-0.99},{id:456,x:0.93,y:-0.36},{id:24,x:-0.72,y:-0.69}];
export function QuantizeLab(){const [xy,setXY]=useState({x:0.8,y:0.25});const [chosen,setChosen]=useState<number|null>(null);const len=Math.hypot(xy.x,xy.y)||1;const normalized={x:xy.x/len,y:xy.y/len};const rank=useMemo(()=>codes.map(c=>({...c,d:Math.hypot(normalized.x-c.x,normalized.y-c.y)})).sort((a,b)=>a.d-b.d),[normalized.x,normalized.y]);const nearest=rank[0];const place=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();setXY({x:((e.clientX-r.left)/r.width-.5)*2.2,y:(.5-(e.clientY-r.top)/r.height)*2.2})};return <div className="vl-lab"><Badge>Eq.2 · L2 normalize 后最近邻量化</Badge><div className="vl-quant-layout"><svg viewBox="0 0 360 300" className="vl-quant-svg" onPointerMove={e=>{if(e.buttons)place(e)}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);place(e)}} aria-label="拖动空间中的 latent 点"><circle cx="180" cy="150" r="110" className="unit-circle"/><line x1="180" y1="150" x2={180+normalized.x*110} y2={150-normalized.y*110} className="vl-quant-line"/>{codes.map(c=><g key={c.id} onClick={()=>setChosen(c.id)} style={{cursor:'pointer'}}><circle cx={180+c.x*110} cy={150-c.y*110} r={nearest.id===c.id?13:10} className={nearest.id===c.id?'nearest':''}/><text x={184+c.x*110} y={144-c.y*110}>#{c.id}</text></g>)}<circle cx={180+normalized.x*110} cy={150-normalized.y*110} r="11" className="latent"/></svg><div className="vl-distance-list">{rank.map((c,i)=><div key={c.id} className={i===0?'first':''}><span>Code #{c.id}</span><b>{c.d.toFixed(3)}</b><i style={{width:`${Math.max(8,(1-c.d/2)*100)}%`}}/></div>)}</div></div><Readout>拖动橙色 latent 点或点击码字。归一化后最近的是 <b>Motion Token #{nearest.id}</b>。{chosen!==null&&<span> 你选择了 Code #{chosen}；{chosen===nearest.id?'与最近邻一致。':<span className="vl-correction">Eq.2 必须选择最小距离码字。</span>}</span>}</Readout><small className="vl-note">二维位置和五个 code 为教学模拟；真实 codebook 有 1024 项，量化前投影到 32 维。</small></div>}

export function SequenceLab({variant}:Props){const [segments,setSegments]=useState<string[]>([]);const [cursor,setCursor]=useState(0);const [show,setShow]=useState(false);const add=(s:string)=>setSegments([...segments,s]);const valid=segments.every((s,i)=>i===0||!(s==='IMG'&&segments[i-1]==='IMG'));const next=segments[cursor]||'尚未添加';return <div className="vl-lab"><Badge>论文证据 · Figure 2 / Eq.5</Badge><div className="vl-choices"><button onClick={()=>add('IMG')}>+ [IMG] visual segment</button><button onClick={()=>add('MOV')}>+ [MOV] motion segment</button><button onClick={()=>add('TEXT')}>+ 文本</button><button onClick={()=>{setSegments([]);setCursor(0)}}>清空</button></div><div className="vl-sequence">{segments.length?segments.map((s,i)=><button key={i} className={`${s.toLowerCase()} ${i===cursor?'selected':''}`} onClick={()=>setCursor(i)}><small>{s==='IMG'?'[IMG]':s==='MOV'?'[MOV]':'[TEXT]'}</small><span>{s==='IMG'?'v₁ v₂ … v₉₀':s==='MOV'?'m₁ m₂ … m₁₃₅':'文字 tokens'}</span><small>{s==='IMG'?'[/IMG]':s==='MOV'?'[/MOV]':'[/TEXT]'}</small></button>):<span className="vl-empty">添加一个成组的 token segment</span>}</div>{variant==='next'&&<div className="vl-next-controls"><button onClick={()=>setCursor(Math.min(Math.max(0,segments.length-1),cursor+1))}>预测下一段 →</button><button onClick={()=>setShow(!show)}>{show?'隐藏':'显示'}上下文</button></div>}<Readout>{segments.length?`当前第 ${cursor+1} 段：${next}。${show?'模型只能依据前面已出现的 tokens 预测下一 token。':''}${valid?'':'相邻图像段通常需要有对应运动段；这里的构造属于教学实验。'}`:'论文 Figure 2 用 [IMG]…[/IMG] 与 [MOV]…[/MOV] 包住成组 tokens；并非 V₁、M₁ 一一交替。'}</Readout></div>}
