import React, { useState } from 'react';

type Props={variant?:string};
const Badge=({children,tone='paper'}:{children:React.ReactNode;tone?:string})=><span className={`vl-badge ${tone}`}>{children}</span>;
const Tabs=({items,value,onChange}:{items:string[];value:string;onChange:(x:string)=>void})=><div className="vl-choices">{items.map(x=><button key={x} className={value===x?'selected':''} onClick={()=>onChange(x)}>{x}</button>)}</div>;
const Note=({children}:{children:React.ReactNode})=><div className="vl-readout">{children}</div>;

export function DetokenizerLab({variant}:Props){const [step,setStep]=useState(0);const [direct,setDirect]=useState(true);const [feature,setFeature]=useState(true);const [sigma,setSigma]=useState(30);const nodes=['Visual tokens → 关键帧 U-Net','Motion tokens → 重建运动向量','Motion input + keyframe latent + noisy video','Motion condition encoder → cross-attention','3D U-Net → 连续视频'];return <div className="vl-lab"><Badge>论文证据 · Figure 3(a) / Eq.3 / Appendix Figure 10</Badge><div className="vl-decoder-grid">{nodes.map((n,i)=><button key={i} className={step===i?'selected':''} onClick={()=>setStep(i)}><b>0{i+1}</b><span>{n}</span></button>)}</div><div className="vl-wire-box"><label><input type="checkbox" checked={direct} onChange={e=>setDirect(e.target.checked)}/> 直接 motion input</label><label><input type="checkbox" checked={feature} onChange={e=>setFeature(e.target.checked)}/> Motion feature cross-attention（EMC）</label></div><div className="vl-decoder-paths"><span>Motion vectors</span><span className={direct?'on':''}>↘ input condition</span><span className={feature?'on':''}>↗ feature condition</span><span>3D U-Net</span></div>{variant==='flow'&&<div className="vl-edm-demo"><label>Eq.3 噪声级别 σ <input type="range" min="0" max="100" value={sigma} onChange={e=>setSigma(+e.target.value)}/><b>{sigma}%</b></label><div className="vl-edm-bars"><span style={{width:`${Math.max(8,sigma)}%`}}/></div><small>橙色区域示意 X₀+n 中的噪声强度；不是实际 EDM 损失数值。</small></div>}<Note>{step===0?'先由视觉 token 解码关键帧；Video-LaVIT 使用与 LaVIT 类似的条件去噪 U-Net。':step===1?'运动 token 被映射回 motion vectors，再用于视频解码。':step===2?'直接路径把 motion vectors、重复的关键帧 latent 和 noisy video 按通道拼接。':step===3?'特征路径由 12-block motion condition encoder 提取运动特征，进入 3D U-Net 的时空 cross-attention。':'3D U-Net 按 Eq.3 的 EDM 目标训练，恢复原视频帧。'} {direct&&feature?'两条条件路径都已连接。':direct&&!feature?'只剩直接输入；这对应 Figure 10 的 w/o EMC 定性消融。':!direct&&feature?'此组合是教学模拟，论文未单独报告。':'没有运动条件；论文未报告这一设置。'}</Note>{variant==='ablate'&&<div className="vl-figure-hint">切换顶部“论文原图”可查看 Appendix Figure 10 的列车与鱼重建对照；该图没有数值指标。</div>}</div>}

export function LongVideoLab({variant}:Props){const [clips,setClips]=useState(2);const [step,setStep]=useState(0);const [constraint,setConstraint]=useState(true);const stage=['上一段的末帧','DDIM 反演 ΔT 步','带噪状态 xΔT','下一关键帧初始噪声'];const add=()=>{const n=Math.min(8,clips+1);setClips(n);window.dispatchEvent(new CustomEvent('vl-clips',{detail:n}))};return <div className="vl-lab"><Badge>Figure 3(b) / Eq.4 / Figure 5</Badge><div className="vl-clip-strip">{Array.from({length:clips},(_,i)=><div key={i} className="vl-clip"><strong>Clip {i+1}</strong><div className="vl-clip-track"><i/><i/><i/><i/></div><small>{i===0?'起始视频':constraint?'边界受约束':'独立解码'}</small></div>)}</div><div className="vl-choices"><button onClick={add} disabled={clips>=8}>+ 下一段 clip</button><button onClick={()=>{setClips(2);window.dispatchEvent(new CustomEvent('vl-clips',{detail:2}))}}>重置</button></div>{variant==='ddim'&&<><div className="vl-stepper"><button onClick={()=>setStep(Math.max(0,step-1))}>←</button>{stage.map((s,i)=><button className={i===step?'selected':''} onClick={()=>setStep(i)} key={s}>{i+1}</button>)}<button onClick={()=>setStep(Math.min(3,step+1))}>→</button></div><div className="vl-stage-caption">{stage[step]}</div></>}{(variant==='noise'||variant==='ddim'||variant==='stitch')&&<label className="vl-toggle"><input type="checkbox" checked={constraint} onChange={e=>setConstraint(e.target.checked)}/> 使用 noise constraint</label>}<Note>{variant==='curve'?`${clips} 段 × (约 90 visual + 135 motion) ≈ ${clips*225} 个内容 tokens；不含文本及特殊标记。论文也指出模型受上下文窗口与训练视频长度限制。`:constraint?'Figure 5 的定性对照显示：从前一末帧反演得到的噪声约束有助于跨 clip 视觉一致性。':'关闭约束的画面变化仅为教学示意；真实 Figure 5 可在论文原图中比较。'}</Note></div>}

const stages=[{name:'Stage 1',title:'训练 Tokenizer + Detokenizer',data:'WebVid-10M 纯视频；Detokenizer 另讨论 InterVid-14M-aesthetics 约 300K 子集',goal:'压缩运动并重建视频；该阶段不使用文本 caption。论文实验结果使用仅 WebVid-10M 的 checkpoint'},{name:'Stage 2',title:'生成式预训练',data:'WebVid-10M + 93M image-text + RedPajama 英文文本',goal:'在 LLM 中联合学习图像、视频、文本 token 的关系'},{name:'Stage 3',title:'指令微调',data:'665K LLaVA-v1.5 image-text + 100K Video-ChatGPT video-text',goal:'改善多模态指令跟随与问答'}];
const configs=[{name:'Language Model',steps:'30K',batch:'2048',gpus:'128 A100',time:'60h',lr:'2e-5 / 5e-5',more:'LaVIT-7B 初始化；2048 输入序列'},{name:'Tokenizer',steps:'100K',batch:'512',gpus:'64 A100',time:'10h',lr:'1e-4',more:'运动码本 1024；投影 32 维；EMA 0.995'},{name:'Detokenizer',steps:'60K',batch:'128',gpus:'64 A100',time:'48h',lr:'5e-5',more:'先 384×384 训练 50K，再高分辨率微调 10K'}];
export function TrainingLab({variant}:Props){const [stage,setStage]=useState(0);const [config,setConfig]=useState(variant==='tok'?1:variant==='det'?2:0);if(variant==='stage')return <div className="vl-lab"><Badge>论文证据 · Section 3.3 / Appendix A.2</Badge><Tabs items={stages.map(x=>x.name)} value={stages[stage].name} onChange={x=>setStage(stages.findIndex(s=>s.name===x))}/><div className="vl-stage-card"><span className="vl-stage-index">0{stage+1}</span><div><h3>{stages[stage].title}</h3><p><strong>数据</strong> {stages[stage].data}</p><p><strong>目标</strong> {stages[stage].goal}</p></div></div><Note>阶段顺序说明训练目的。30K / 100K / 60K 是 Table 8 中三个模块各自的训练步数，不能当作三个 Stage 的时长比例。</Note></div>;const idx=config;return <div className="vl-lab"><Badge>论文证据 · Table 8 / Appendix A.1</Badge><Tabs items={configs.map(x=>x.name)} value={configs[idx].name} onChange={x=>setConfig(configs.findIndex(c=>c.name===x))}/><div className="vl-config-grid">{[['Training steps',configs[idx].steps],['Global batch',configs[idx].batch],['GPU',configs[idx].gpus],['Training time',configs[idx].time],['Peak LR',configs[idx].lr]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><Note>{configs[idx].more}。这些是模块配置，不代表三阶段的独立运行时间。</Note></div>}

type Score={name:string;value:number};
export type Metric={source:string;protocol:string;direction:'↑'|'↓';rows:Score[];explain:string};
const imageData:Record<string,Metric>={
  'VQAv2':{source:'Table 1',protocol:'VQAv2 图像问答；表中 * 表示训练数据可能重叠。',direction:'↑',rows:[{name:'Video-LaVIT',value:80.3},{name:'LLaVA-1.5',value:78.5},{name:'LLaMA-VID',value:78.3},{name:'Video-LLaVA',value:74.7}],explain:'同样的指令数据与基础模型条件下，Video-LaVIT 为 80.3。'},
  'GQA':{source:'Table 1',protocol:'GQA 图像问答；* 表示训练数据可能重叠。',direction:'↑',rows:[{name:'Video-LaVIT',value:64.4},{name:'LLaMA-VID',value:63.0},{name:'LLaVA-1.5',value:62.0},{name:'Video-LLaVA',value:60.3}],explain:'需同时看输入分辨率和训练条件。'},
  'VizWiz':{source:'Table 1',protocol:'VizWiz 图像问答准确率。',direction:'↑',rows:[{name:'Video-LaVIT',value:56.0},{name:'LLaMA-VID',value:52.5},{name:'LLaVA-1.5',value:50.0},{name:'Video-LLaVA',value:48.1}],explain:'论文在此项报告 56.0。'},
  'ScienceQA-IMG':{source:'Table 1',protocol:'ScienceQA-IMG 图像题准确率。',direction:'↑',rows:[{name:'Video-LaVIT',value:70.0},{name:'LLaMA-VID',value:67.7},{name:'LLaVA-1.5',value:66.8},{name:'Video-LLaVA',value:66.4}],explain:'Video-LaVIT 比 LLaVA-1.5 高 3.2 个百分点。'},
  'MME':{source:'Table 1',protocol:'MME 总分；不是百分比。',direction:'↑',rows:[{name:'Video-LaVIT',value:1551.8},{name:'LLaVA-1.5',value:1510.7},{name:'LLaMA-VID',value:1405.6}],explain:'Video-LLaVA 在 Table 1 未报告此项，故不画零值。'},
  'MMBench':{source:'Table 1',protocol:'MMBench 评测分数。',direction:'↑',rows:[{name:'Video-LaVIT',value:67.3},{name:'LLaMA-VID',value:65.3},{name:'LLaVA-1.5',value:64.3},{name:'Video-LLaVA',value:60.9}],explain:'只比较 Table 1 报告的模型。'},
  'SEED':{source:'Table 1',protocol:'SEED 评测分数。',direction:'↑',rows:[{name:'Video-LaVIT',value:64.0},{name:'LLaMA-VID',value:59.7},{name:'LLaVA-1.5',value:58.6}],explain:'Video-LLaVA 在 Table 1 未报告此项。'},
  'MM-Vet':{source:'Table 1',protocol:'MM-Vet 评测分数。',direction:'↑',rows:[{name:'Video-LaVIT',value:33.2},{name:'Video-LLaVA',value:32.0},{name:'LLaVA-1.5',value:30.5}],explain:'LLaMA-VID 在 Table 1 未报告此项。'}
};
const videoData:Record<string,Metric>={
  'MSVD-QA':{source:'Table 2',protocol:'零样本 Video QA；GPT-3.5 辅助判分的 Accuracy。',direction:'↑',rows:[{name:'Video-LaVIT',value:73.2},{name:'Video-LLaVA',value:70.7},{name:'LLaMA-VID',value:69.7},{name:'Video-ChatGPT',value:64.9}],explain:'论文也报告 GPT 相对评分；这张图只画 Accuracy。'},
  'MSRVTT-QA':{source:'Table 2',protocol:'零样本 Video QA；GPT-3.5 辅助判分的 Accuracy。',direction:'↑',rows:[{name:'Video-LaVIT',value:59.3},{name:'Video-LLaVA',value:59.2},{name:'LLaMA-VID',value:57.7},{name:'Video-ChatGPT',value:49.3}],explain:'Video-LaVIT 准确率最高，但 GPT 相对评分低于 Video-LLaVA。'},
  'ActivityNet-QA':{source:'Table 2',protocol:'零样本 Video QA；GPT-3.5 辅助判分的 Accuracy。',direction:'↑',rows:[{name:'Video-LaVIT',value:50.1},{name:'LLaMA-VID',value:47.4},{name:'Video-LLaVA',value:45.3},{name:'Video-ChatGPT',value:35.2}],explain:'动作相关任务有助于观察 motion tokens 的价值。'},
  'Perception Test':{source:'Table 3',protocol:'Perception Test 测试集的零样本准确率。',direction:'↑',rows:[{name:'Video-LaVIT',value:47.9},{name:'VideoChat2',value:47.3},{name:'BLIP-2',value:39.2},{name:'Flamingo',value:33.5}],explain:'此处 baseline 与 Table 2 不同，不能混成一组。'},
  'EgoSchema':{source:'Table 3',protocol:'EgoSchema 测试集的零样本准确率。',direction:'↑',rows:[{name:'Video-LaVIT',value:37.3},{name:'InternVideo',value:32.1},{name:'mPLUG-Owl',value:28.7},{name:'FrozenBiLM',value:26.9}],explain:'论文使用跨 64 秒的 16 个关键帧及其中间运动向量。'}
};
const generationData:Record<string,Metric>={
  'MSR-VTT FVD':{source:'Table 4',protocol:'MSR-VTT 零样本文生视频；训练数据规模不同。',direction:'↓',rows:[{name:'Video-LaVIT',value:188.36},{name:'VideoPoet',value:213},{name:'VideoComposer',value:580},{name:'CogVideo',value:1294}],explain:'论文报告 Video-LaVIT 在 MSR-VTT FVD 上有竞争力。'},
  'MSR-VTT CLIPSIM':{source:'Table 4',protocol:'MSR-VTT 的视频文本语义相似度。',direction:'↑',rows:[{name:'Video-LaVIT',value:0.3012},{name:'VideoPoet',value:0.3049},{name:'VideoComposer',value:0.2932},{name:'CogVideo',value:0.2631}],explain:'CLIPSIM 不是最优，不能只看 FVD 得出全面领先。'},
  'MSR-VTT FID':{source:'Table 4',protocol:'MSR-VTT 帧级 FID；低者好。',direction:'↓',rows:[{name:'Video-LaVIT',value:11.27},{name:'Make-A-Video',value:13.17},{name:'CogVideo',value:23.59}],explain:'仅展示 Table 4 中报告了 FID 的可比行。'},
  'UCF-101 IS':{source:'Table 4',protocol:'UCF-101 的视频 Inception Score。',direction:'↑',rows:[{name:'Video-LaVIT',value:44.26},{name:'PYoCo',value:47.76},{name:'VideoPoet',value:38.44},{name:'CogVideo',value:25.27}],explain:'PYoCo 的 IS 高于 Video-LaVIT。'},
  'UCF-101 FVD':{source:'Table 4',protocol:'UCF-101 零样本视频生成 FVD。',direction:'↓',rows:[{name:'Video-LaVIT',value:280.57},{name:'SVD',value:242.02},{name:'VideoPoet',value:355.00},{name:'CogVideo',value:701.59}],explain:'SVD 的 FVD 更低；训练数据规模与目标不同。'}
};
const longData:Record<string,Metric>={
  FVD:{source:'Table 5',protocol:'EvalCrafter 提示生成 2048 个 64 帧视频。',direction:'↓',rows:[{name:'Video-LaVIT',value:113.37},{name:'FreeNoise',value:85.83},{name:'Gen-L-Video',value:177.63},{name:'Sliding',value:224.55}],explain:'FreeNoise 的 FVD 更低。'},
  KVD:{source:'Table 5',protocol:'EvalCrafter 提示生成 2048 个 64 帧视频。',direction:'↓',rows:[{name:'Video-LaVIT',value:4.94},{name:'FreeNoise',value:6.07},{name:'Gen-L-Video',value:21.06},{name:'Sliding',value:44.09}],explain:'KVD 比较长视频前后片段的分布差异；Video-LaVIT 在表中最低。'},
  CLIPSIM:{source:'Table 5',protocol:'EvalCrafter 提示生成 2048 个 64 帧视频。',direction:'↑',rows:[{name:'Video-LaVIT',value:0.9621},{name:'FreeNoise',value:0.9732},{name:'Gen-L-Video',value:0.9370},{name:'Sliding',value:0.9438}],explain:'FreeNoise 的 CLIPSIM 更高。'}
};
export const modes:Record<string,Record<string,Metric>>={'图像理解':imageData,'视频理解':videoData,'视频生成':generationData,'长视频':longData};
const defaults:Record<string,string>={'图像理解':'VQAv2','视频理解':'MSVD-QA','视频生成':'MSR-VTT FVD','长视频':'KVD'};
export function ArenaLab({variant}:Props){const [tab,setTab]=useState(variant==='long'?'长视频':'视频理解');const [metric,setMetric]=useState(variant==='long'?'KVD':'MSVD-QA');const mode=variant==='under'?'视频理解':variant==='long'?'长视频':tab;const selected=modes[mode][metric]||modes[mode][defaults[mode]];const max=Math.max(...selected.rows.map(r=>r.value));return <div className="vl-lab"><Badge>论文证据 · {selected.source}</Badge>{variant!=='under'&&variant!=='long'&&<Tabs items={Object.keys(modes)} value={tab} onChange={x=>{setTab(x);setMetric(defaults[x])}}/>}<Tabs items={Object.keys(modes[mode])} value={metric} onChange={setMetric}/><div className="vl-metric-heading"><strong>{metric}</strong><span>{selected.direction} {selected.direction==='↓'?'越低越好':'越高越好'}</span></div><div className="vl-arena-bars">{selected.rows.map(r=><div key={r.name} className={r.name==='Video-LaVIT'?'ours':''}><span>{r.name}</span><div><i style={{width:`${Math.max(5,r.value/max*100)}%`}}/></div><b>{r.value}</b></div>)}</div><Note>{selected.protocol} {selected.explain} 柱长只用于当前指标，不拼成综合分。</Note></div>}

const motionRows=[['MSVD ↑',67.3,73.2],['ActivityNet ↑',47.4,50.1],['UCF-101 IS ↑',29.56,44.26],['UCF-101 FVD ↓',442.80,280.57]] as const;
const countRows=[['MSVD ↑',69.2,73.2],['ActivityNet ↑',48.8,50.1],['UCF-101 IS ↑',37.57,44.26],['UCF-101 FVD ↓',281.24,280.57]] as const;
export function AblationLab({variant}:Props){const [kind,setKind]=useState('Motion on/off');const [risk,setRisk]=useState('长视频长度');const [choice,setChoice]=useState(()=>{try{return localStorage.getItem('vl-final-choice')||''}catch{return ''}});if(variant==='review')return <div className="vl-lab"><Badge tone="extension">Reviewer Mode · 论文局限</Badge><Tabs items={['长视频长度','训练数据','生成风险','计算成本']} value={risk} onChange={setRisk}/><div className="vl-stage-card"><span className="vl-stage-index">?</span><div><h3>{risk}</h3><p>{risk==='长视频长度'?'Appendix C 指出受 4096 context window 与训练视频长度限制，模型不能生成很长的视频。':risk==='训练数据'?'仅用 WebVid-10M 做视频预训练；视频平均约 15 秒且场景变化少，可能导致不同 clip 关键帧相似。':risk==='生成风险'?'Impact Statement 提到幻觉、偏见、有害回答及个性化生成造成虚假信息的风险。':'Appendix C 明确提到训练成本仍高，扩展到网络规模视频需要进一步优化。'}</p></div></div><Note>先区分论文作者明确写出的限制与我们自己的延伸问题；例如“motion editing”是延伸推演，不是本文实测能力。</Note></div>;
if(variant==='final')return <div className="vl-lab"><Badge tone="demo">本地选择 · 无服务器</Badge><p>以下哪项最能概括论文的核心？</p><Tabs items={['逐帧堆叠视觉 token','I-frame + motion vector 解耦，再统一自回归建模','直接用 3D U-Net 训练 LLM']} value={choice} onChange={x=>{setChoice(x);localStorage.setItem('vl-final-choice',x)}}/><Note>{choice?choice.startsWith('I-frame')?'✓ 正确。压缩视频提供关键帧与运动；两支离散化后成为 LLM 序列。':'小 V：再回到 Figure 2，看看视觉与运动是如何分开的。':'选择后在此设备保存并显示论文答案。'}</Note></div>;
return <div className="vl-lab"><Badge>论文证据 · Table 6 / Table 7 / Figure 10</Badge><Tabs items={['Motion on/off','135 vs 256 tokens','EMC on/off']} value={kind} onChange={setKind}/>{kind==='EMC on/off'?<div className="vl-stage-card"><span className="vl-stage-index">EMC</span><div><h3>Figure 10 定性重建</h3><p>去掉 motion feature cross-attention 后，仅以 motion vectors 为直接输入；论文示例中的列车和鱼几乎不动。此实验没有 FVD 数值。</p></div></div>:<div className="vl-ablation-table"><div className="head"><span>指标</span><span>{kind==='Motion on/off'?'w/o motion':'N=256'}</span><span>{kind==='Motion on/off'?'w/ motion':'N=135'}</span></div>{(kind==='Motion on/off'?motionRows:countRows).map(([name,a,b])=><div key={name}><span>{name}</span><b>{a}</b><b className="ours">{b}</b></div>)}</div>}<Note>{kind==='Motion on/off'?'Table 6 中两种基线的设置因任务而异：理解任务使用均匀采样帧；生成任务先文生图再使用 SVD img2vid-xt。':kind==='135 vs 256 tokens'?'Table 7 仅比较 256 和 135 两个离散设置；不能据此绘制任意 token 数的连续性能曲线。':'Figure 10 支持 EMC 改善视频重建保真度的定性判断，不能推出所有任务的数值提升。'}</Note></div>}

export function EvidenceLab(){const [mode,setMode]=useState('PAPER');return <div className="vl-lab"><Tabs items={['PAPER','DEMO','EXTENSION']} value={mode} onChange={setMode}/><div className="vl-stage-card"><span className="vl-stage-index">{mode[0]}</span><div><h3>{mode==='PAPER'?'论文证据':mode==='DEMO'?'教学模拟':'延伸推演'}</h3><p>{mode==='PAPER'?'原文 Figure、Table、Equation 或 Appendix 明确报告的配置与结果。':mode==='DEMO'?'把论文机制压成可操作的二维演示；位置、动画和中间数值不等于模型输出。':'根据论文机制提出的新应用或研究问题；需要新实验验证。'}</p></div></div><Note>先看标签，再判断一个动画能否当成实验证据。</Note></div>}
